// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7yVoaa7OacuwPN-CBTX2jOw8HwDF_F8k',
    appId: '1:213992092143:web:0f4a0f90cbc8b38c83861a',
    messagingSenderId: '213992092143',
    projectId: 'dextertask',
    authDomain: 'dextertask.firebaseapp.com',
    storageBucket: 'dextertask.appspot.com',
    measurementId: 'G-RNKFG321BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTeGmkZ13P4TxQ-QGGPEQWexaY5Ts5kM',
    appId: '1:213992092143:android:e604979abcb2515083861a',
    messagingSenderId: '213992092143',
    projectId: 'dextertask',
    storageBucket: 'dextertask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoU-PTnfhwsZ8Ux3MZ5k0qqS1AH2LC98Q',
    appId: '1:213992092143:ios:0e1f58de6f77db0a83861a',
    messagingSenderId: '213992092143',
    projectId: 'dextertask',
    storageBucket: 'dextertask.appspot.com',
    iosClientId: '213992092143-7inrodv7mmqalc73b2nkg5uij8l3npu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dexterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoU-PTnfhwsZ8Ux3MZ5k0qqS1AH2LC98Q',
    appId: '1:213992092143:ios:0e1f58de6f77db0a83861a',
    messagingSenderId: '213992092143',
    projectId: 'dextertask',
    storageBucket: 'dextertask.appspot.com',
    iosClientId: '213992092143-7inrodv7mmqalc73b2nkg5uij8l3npu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dexterTask',
  );
}
